--[[
    @file   settings.lua
    @author Sebastien LEGRAND
    @email  oaxley@gmail.com
    @date   2012-07-30
    
    @brief  Pong Game settings
  ]]

----------[ module settings ]----------
module(..., package.seeall)


----------[ globals ]----------
SCREEN_MAX_X = display.contentWidth
SCREEN_MAX_Y = display.contentHeight

BALL_SIZE = 10
BALL_INIT_X = (SCREEN_MAX_X - BALL_SIZE) / 2
BALL_INIT_Y = (SCREEN_MAX_Y - BALL_SIZE) / 2
BALL_MAX_VELOCITY = 6

PADDLE_WIDTH  = 10
PADDLE_HEIGHT = SCREEN_MAX_Y / 6
PADDLE_INIT_POSITION = (SCREEN_MAX_Y - PADDLE_HEIGHT) / 2
PADDLE_EDGE_SPACE = 15

TABLE_EDGE_THICKNESS = 10
TABLE_ALPHA_VALUE = 0.5
TABLE_REDUCTION_RATIO = 10

MIDDLE_LINE_STEPS = 25

PLAYER1_POSITION_X = PADDLE_EDGE_SPACE
PLAYER1_POSITION_Y = PADDLE_INIT_POSITION

PLAYER2_POSITION_X = SCREEN_MAX_X - PADDLE_EDGE_SPACE - PADDLE_WIDTH
PLAYER2_POSITION_Y = PADDLE_INIT_POSITION

SCOREBOARD_POSITION_Y       = TABLE_EDGE_THICKNESS + 25
SCOREBOARD_DIGIT_BLOCK_SIZE = 10
SCOREBOARD_DIGIT_NUM_BLOCKS = 5
SCOREBOARD_DIGIT_WIDTH      = SCOREBOARD_DIGIT_NUM_BLOCKS * SCOREBOARD_DIGIT_BLOCK_SIZE
SCOREBOARD_DIGIT_HEIGHT     = SCOREBOARD_DIGIT_NUM_BLOCKS * SCOREBOARD_DIGIT_BLOCK_SIZE
SCOREBOARD_DIGIT_SPACE      = SCOREBOARD_DIGIT_BLOCK_SIZE
SCOREBOARD_MARGIN           = 2 * SCOREBOARD_DIGIT_BLOCK_SIZE

WINNING_SCORE = 10